spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/final_project
    username: postgres
    password: postgres

logbook:
  filter.enabled: true
  format.style: http
  write:
    max-body-size: 1000

final:
  project:
    testProperty: siemanko