spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/final_project
    username: postgres
    password: postgres


final:
  project:
    testProperty: siemanko